apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ping_pong/manifests/namespace.yaml
- log_output/manifests/deployment.yaml
- log_output/manifests/configmap.yaml
- log_output/manifests/gateway-route.yaml
- ping_pong/manifests/deployment.yaml
- ping_pong/manifests/postgres.yaml

images:
- name: log-generator
  newName: gedionkip/k8s-submissions
  newTag: log-generator-50ab88c1efec1736bd6f038382de5e415046de95
- name: log-reader
  newName: gedionkip/k8s-submissions
  newTag: log-reader-50ab88c1efec1736bd6f038382de5e415046de95
- name: ping-pong-app
  newName: gedionkip/k8s-submissions
  newTag: 4.1.0
