apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: project
stringData:
  POSTGRES_PASSWORD: StrongP@ssw0rd
---
apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
  namespace: project
stringData:
  BROADCASTER_URL: https://discord.com/api/webhooks/GENERIC/PLACEHOLDER
