apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-staging

resources:
  - ../../base

patches:
  - path: pvc.yaml
    target:
      kind: PersistentVolumeClaim
      name: todo-app-pvc
  - path: postgres.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: postgres-db
  - path: ingress.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: the-project
  - path: broadcaster-json.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: broadcaster

images:
  - name: curlimages/curl
    newTag: latest
  - name: postgres
    newTag: "17"
  - name: todo-app
    newName: gedionkip/k8s-submissions
    newTag: "4.5"
  - name: todo-backend
    newName: gedionkip/k8s-submissions
    newTag: "4.6.1"
  - name: broadcaster-image
    newName: gedionkip/k8s-submissions
    newTag: "broadcaster-v3"
