apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-prod

resources:
  - ../../base
  - backup-cronjob.yaml

images:
  - name: curlimages/curl
    newTag: latest
  - name: postgres
    newTag: "17"
  - name: todo-app
    newName: gedionkip/k8s-submissions
    newTag: "4.5"
  - name: todo-backend
    newName: gedionkip/k8s-submissions
    newTag: "4.6.1"
  - name: broadcaster-image
    newName: gedionkip/k8s-submissions
    newTag: "broadcaster-v3"
