apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  labels:
    app: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
      - name: shared-logs
        persistentVolumeClaim:
          claimName: shared-data-pvc
      containers:
      - name: log-output-generator
        image: gedionkip/k8s-submissions:1.11.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: shared-logs
          mountPath: /shared
        env:
        - name: STATUS_FILE
          value: "/shared/status.log"
      - name: log-output-reader
        image: gedionkip/k8s-submissions:1.11.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: shared-logs
          mountPath: /shared
        env:
        - name: STATUS_FILE
          value: "/shared/status.log"
        - name: COUNT_FILE
          value: "/shared/count.log"

---
apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
spec:
  type: ClusterIP
  selector:
    app: log-output
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
