apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/dummysite-crd.yaml
  - manifests/rbac.yaml
  - manifests/controller-deployment.yaml

images:
  - name: dummy-controller
    newName: gedionkip/k8s-submissions
    newTag: dummy-controller-v1